すべてのパッケージを取得する処理を追加

diff --git a/script/travis/check_packages b/script/travis/check_packages
--- a/script/travis/check_packages
+++ b/script/travis/check_packages
@@ -8,7 +8,13 @@ source ./lib/utils.sh
 repo_dir=tmp/bekobrew-packages
 git clone --single-branch -b misc git://github.com/sh19910711/bekobrew-packages.git ${repo_dir}
 
-for package_name in `get_all_package_names`; do
-  grep ${package_name} ${repo_dir}/${GOOD_PACKAGE_LIST_FILENAME} || exit 1
+for package_name in `get_all_package_fullnames`; do
+  grep ${package_name} ${repo_dir}/${GOOD_PACKAGE_LIST_FILENAME}
+  local ret=$?
+  if [ $? -eq 0 ]; then
+    echo "${package_name}: Passed"
+  else
+    echo "${package_name}: Failed"
+  fi
 done
 
